### ISSUE TITLE
Sugestão: Apresentações

### ISSUE THREAD

**Issue by Spacial** [leg-ufpr/rday#1]
Sugestão:

Disponibilizar as apresetanções em uma pasta do repo.

**Comment by fernandomayer** [comment]
Foi criado um diretório e uma página exclusiva para os materiais (ref 8e61db30f32249835a1ee6b0c4f7b64b03efc384).

Os apresentadores já foram contactados para enviar o material ou fazer um PR por aqui.

Obrigado.

**Comment by Spacial** [comment]
valeu @fernandomayer , obrigado!
